import board
from adafruit_hid.keycode import Keycode
from adafruit_hid.mouse import Mouse

pin_map = {
    0: board.GP0,
    1: board.GP1,
    2: board.GP2,
    3: board.GP3,
    4: board.GP4,
    5: board.GP5,
    6: board.GP6,
    7: board.GP7,
    8: board.GP8,
    9: board.GP9,
    10: board.GP10,
    11: board.GP11,
    12: board.GP12,
    13: board.GP13,
    14: board.GP14,
    15: board.GP15,
    16: board.GP16,
    17: board.GP17,
    18: board.GP18,
    19: board.GP19,
    20: board.GP20,
    21: board.GP21,
    22: board.GP22,
    # 23: board.GP23,
    # 24: board.GP24,
    # 25: board.GP25,
    26: board.GP26,
    27: board.GP27,
    28: board.GP28,
    # 29: board.GP29,
}

action_map = {
    "Keycode": {
        "LEFT_ARROW": Keycode.LEFT_ARROW,
        "RIGHT_ARROW": Keycode.RIGHT_ARROW,
        "ESCAPE": Keycode.ESCAPE,
        "LEFT_BRACKET": Keycode.LEFT_BRACKET,
        "RIGHT_BRACKET": Keycode.RIGHT_BRACKET,
        "ENTER": Keycode.ENTER,
        "A": Keycode.A,
        "B": Keycode.B,
        "C": Keycode.C,
        "D": Keycode.D,
        "E": Keycode.E,
        "F": Keycode.F,
        "G": Keycode.G,
        "H": Keycode.H,
        "I": Keycode.I,
        "J": Keycode.J,
        "K": Keycode.K,
        "L": Keycode.L,
        "M": Keycode.M,
        "N": Keycode.N,
        "O": Keycode.O,
        "P": Keycode.P,
        "Q": Keycode.Q,
        "R": Keycode.R,
        "S": Keycode.S,
        "T": Keycode.T,
        "U": Keycode.U,
        "V": Keycode.V,
        "W": Keycode.W,
        "X": Keycode.X,
        "Y": Keycode.Y,
        "Z": Keycode.Z,
    },
    "Mouse":{
        "LEFT_BUTTON": Mouse.LEFT_BUTTON,
    }
}
